import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import ChatSupport from "@/components/chat/chat-support";
import Examples from "@/components/examples";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="flex h-[calc(100dvh)] flex-col items-center justify-center md:px-24 gap-4">

            <div className="z-10 border rounded-lg w-full max-h-screen h-[90%]  text-sm flex">
              {children}
              <Toaster/>
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
